### ISSUE TITLE
Digital audio noise in end track

### ISSUE THREAD

**Issue by fabiodj2** [angusmack/CDJ-1000Mk3-MCU-Mod#1]
Hello everyone ... I've done my design step and it's almost all working ...

I am printing the case for the STM board and very eager to get everything ready. I was testing all the functions and I noticed a big one, I believe that it could be some problem in my STM, so I would like you to do a test in the same way that I like in the video below:

https://youtu.be/iJTq9NwelFo

The problem is a digital noise whenever the Track is finished and the CDJ Pitch is out of 00.00%.

Has anyone else had this problem?

Thank you Very much!!!

**Comment by jrsmi9** [comment]
Hi, I have finished building 2 now, both of them have this same issue.
However I was not worried about it as it only occurs after the song is finished playing, by which time the channel faders on the mixer are down and the song is completely mixed out.

**Comment by jrsmi9** [comment]
nice job with the tssop board you made by the way, it is much cleaner than mine!

**Comment by fabiodj2** [comment]
Hi...I'm working on the electronic part, how to make printed circuit board and do some mechanical and electronic adjustments in the set to become more friendly to do the complete design. 

In the internal part of the CDJ control, for example, I will install a flatcable with female and male connector, in the part of the board TSOIP I used a circuit board already with holes and double face. I made the 3D impression of the Case in ABS for added strength. 

In my project I will make the Kit be reversible, that is, if the person wants to return the CDJ 1000 MK3 to its original state it will be possible! 

If I can help and contribute with this electronic part, I am available, even if they want soon I will be able to send to you the circuit boards ready to level near professional. I am very excited about the project and spending enough time and energy to see it close to 100%.

**Comment by angusmack** [comment]
Hi - thank you for raising the concerns about the digital noise. 

Unfortunately family and work does not allow me time to work on this at the moment :-( 

I have complete electronic components for 2 mods, 2 CDJ1000Mk3 I bought from eBay a few months ago sitting at home ready to modify. 

I have got as far as getting a development environment setup and I am able to build and deploy the firmware to the MCU and I have started on the electronic by soldering the TSOP board.

Please - if you have PCBs and design for simplifying the electronics side of things then please do share. The PCB files shared originally that I have in this repo are incomplete and I tried to get them in a format that a PCB printing house would accept but I kept getting validation errors (around solder masks etc.)

So, if you can share your findings please do upload them to this repo and share what you can. I am really looking forward to getting mine modded. 

I have also been looking at micro SD to SD card sockets, to mount on the top/side of the case, as well as a micro USB to USB A socket to also mount in an easy to access position to allow Nexus-style ease of use.

I look forward to seeing all your input. I am just frustrated that I do not really have the time right now.

**Comment by jrsmi9** [comment]
With regard to the errors with the PCB files shared originally, the company I used was: https://www.allpcb.com/

The format was fine according to allpcb, and they printed with no trouble, however I had them printed with no soldermask/drilling etc, just plain copper traces, so it may be different if you wanted something other than plain copper traces. I hope that helps.

Also with the micro sd to sd socket, i used a flat ribbon extension cable like this one:
(micro SD-SD)
https://www.ebay.com.au/itm/Micro-SD-TO-SD-Card-Extension-Cable-Adapter-Extender-Converter-for-SD-RS-MMC-SDH/162837010654?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

or this one: (micro SD-micro SD extension)
https://www.ebay.com.au/itm/Micro-SD-TO-TF-Memory-Card-Extension-Cable-Adapter-Extender-Converter-For-GPS-AU/283378436231?ssPageName=STRK%3AMEBIDX%3AIT&var=584344395468&_trksid=p2057872.m2749.l2649

I then removed the original CDJ 1000 mk3 SD card circuit board, and placed the extension cable in its spot so it is all tucked away neatly. The 3D printed case files I made are sized to fit those extension cables correctly.
Ill take a photo when I'm back home to show it properly to you all

**Comment by fabiodj2** [comment]
HI jrsmi9...Excellent shared tips ... as incredible as it seems I did the same as you with regards to the CF Card extender ... I believe that this way the project gets really good. I only had a slight problem of "interference" using the extender, every time I'm using it the Tag List page opens itself. I'm investigating what might be happening.

**Comment by jrsmi9** [comment]
[Vinyl Label.pdf](https://github.com/angusmack/CDJ-1000Mk3-MCU-Mod/files/3037951/Vinyl.Label.pdf)
Hi again, I forgot to share this earlier:
Because the case I designed to be 3D printed does not have the exact same dimensions as the one Andrei specified in his manual, I also had to re-size and change the vinyl sticker a little so that it fits the STL case file properly. Have attached the modified one that fits the STL file here (hopefully) :)

**Comment by vincentdallamacchia** [comment]
ciao a tutti ... sto aspettando di ricevere il cdj 1000 nk3 per poter fare la mod ...ho già completato le schede stm e anchio ho riscontrato questa interferenza della pagina tag list che a volte si apre da sola .... so che al momento non ci sono ancora loop e hot cue ... qualcuno ha delle novità su firmware nuovi con nuove funzioni ??grazie

**Comment by jrsmi9** [comment]
I tried to post this the other day but it did not work, however here is the vinyl sticker pdf for the 3D printed case files, as the STL file I designed has slightly different dimensions to the case Andrei originally specified in his manual
[Vinyl Label.pdf](https://github.com/angusmack/CDJ-1000Mk3-MCU-Mod/files/3051494/Vinyl.Label.pdf)

**Comment by angusmack** [comment]
> With regard to the errors with the PCB files shared originally, the company I used was: https://www.allpcb.com/
> 
> The format was fine according to allpcb, and they printed with no trouble, however I had them printed with no soldermask/drilling etc, just plain copper traces, so it may be different if you wanted something other than plain copper traces. I hope that helps.
> 
I tried to submit and got the following error from them:

"There is no trace and drills in files，please kindly provide gerber files as RS-274-X TYPE"

![allpcb - pcb error](https://user-images.githubusercontent.com/4437173/56284353-26cd4780-610c-11e9-9412-0ef6ab8af8c2.png)

> I then removed the original CDJ 1000 mk3 SD card circuit board, and placed the extension cable in its spot so it is all tucked away neatly. The 3D printed case files I made are sized to fit those extension cables correctly.
> Ill take a photo when I'm back home to show it properly to you all

Please do share this. Can you upload into the images folder please? 

Also, if you want to edit the main page or add as new page with your method and results then please do this also.

**Comment by jrsmi9** [comment]
Yes, I emailed them saying i didn't require drills, however I'm not sure about file type?
Also I get an error saying i require push access to the repository in order to upload the image files, sorry I've not much experience with git hub

I'll comment them here in the meantime


[SD.zip](https://github.com/angusmack/CDJ-1000Mk3-MCU-Mod/files/3090078/SD.zip)
![micro sd ribbon cable](https://user-images.githubusercontent.com/17604632/56295097-96285300-616f-11e9-8c5d-231b72f99e84.jpg)
![micro sd ribbon cable 2](https://user-images.githubusercontent.com/17604632/56295100-96c0e980-616f-11e9-9a79-05ccce13bb38.jpg)
![SD location](https://user-images.githubusercontent.com/17604632/56295101-96c0e980-616f-11e9-9879-1841ce533d70.jpg)
![SD location 2](https://user-images.githubusercontent.com/17604632/56295102-97598000-616f-11e9-8833-6ba6977dd2af.jpg)

**Comment by jrsmi9** [comment]
The only reason I can think of for the trace, is on their website did you tick the solder mask section as 'none' while uploading?

**Comment by fabiodj2** [comment]
First version of PCB and Skin for CDJ...
![WhatsApp Image 2019-04-17 at 21 49 06](https://user-images.githubusercontent.com/39027217/56381405-2657ae00-61eb-11e9-82f9-b84b655a45d6.jpeg)
![WhatsApp Image 2019-04-15 at 12 39 51](https://user-images.githubusercontent.com/39027217/56381408-28217180-61eb-11e9-858d-52aeec1afec2.jpeg)
![WhatsApp Image 2019-04-15 at 12 33 00](https://user-images.githubusercontent.com/39027217/56381412-29eb3500-61eb-11e9-831a-10ad8a1fce07.jpeg)

**Comment by DJJuciel** [comment]
Good night everyone, all right?
I hope you are all well! ... ah I apologize for my English, because I am using the translator ... so, I saw Fabio Lisboa's video and photos of everyone who shared here, and I noticed the TSSOP to DIP sign from you , ours were very good, if you don't mind, you could make the scheme available or, send photos of how you did it, in the electronics I'm curious or hobbyist, and our plate of you were top, much better than the one in the documentation, if you can send me I will be forever grateful! my email:
deejayjuciel@gmail.com

**Comment by ghost** [comment]
> First version of PCB and Skin for CDJ... ![WhatsApp Image 2019-04-17 at 21 49 06](https://user-images.githubusercontent.com/39027217/56381405-2657ae00-61eb-11e9-82f9-b84b655a45d6.jpeg) ![WhatsApp Image 2019-04-15 at 12 39 51](https://user-images.githubusercontent.com/39027217/56381408-28217180-61eb-11e9-858d-52aeec1afec2.jpeg) ![WhatsApp Image 2019-04-15 at 12 33 00](https://user-images.githubusercontent.com/39027217/56381412-29eb3500-61eb-11e9-831a-10ad8a1fce07.jpeg)

Hello would it be possible to order the same creation from you, because I don't know how to do it please thank you.

**Comment by fabiodj2** [comment]
> 

Hi,

I have the PCB kits ready and tested for the CDJs.  If you want and don't have experience with electronics, I can send you the ready set.

Please look this....

Algumas partes do Kit CDJ 1000 Nexus...agora vamos montar....ufaaaa 🎚️🎛️🎚️

https://www.instagram.com/p/CM-pbR3FhfP/?utm_medium=share_sheet
